### ISSUE TITLE
psutil.Process().rlimit absent

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/psutil-feedstock#47]
Issue:

Code involving [`psutil.Process().rlimit`](https://psutil.readthedocs.io/en/latest/#psutil.Process.rlimit) fails on Linux:
```python
>>> import psutil
>>> psutil.Process().rlimit
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    psutil.Process().rlimit
AttributeError: 'Process' object has no attribute 'rlimit'
```

The reason for this is that psutil only compiles resource limits code on linux with [kernel>=2.6.36 and glibc>=13](https://github.com/giampaolo/psutil/blob/e1ea2bccf8aea404dca0f79398f36f37217c45f6/psutil/_psutil_linux.c#L45-L49)

The conda-forge build of psutil is [built on a docker container](https://github.com/conda-forge/psutil-feedstock/blob/426d92dc5c374f05bdd1d0f98248822788100397/.azure-pipelines/azure-pipelines-linux.yml#L13-L16) that runs off [CentOS 6](https://github.com/conda-forge/docker-images/blob/0b8d9f4d9f31728634cfcce82aaec4cd617c8513/linux-anvil-comp7/Dockerfile#L1), which means glibc=2.12 and kernel=2.6.32.

Thus
```python
>>> import psutil._pslinux
>>> psutil._pslinux.HAS_PRLIMIT
False
```
and that is why there is no `.rlimit` on conda-forge psutil.

I appreciate that this is not a psutil package maintainer issue, and that there will be no quick fix. Does anyone here know if/when conda-forge will update the build docker container platform, or who I can ask about this?

**Comment by nehaljwani** [comment]
xref: https://github.com/conda-forge/conda-forge.github.io/issues/900

**Comment by jakirkham** [comment]
Yeah as Nehal pointed out there is some work in this direction. Though it's worth noting this is not quite as simple as flipping a switch ;) We will get there though :)

**Comment by Anthchirp** [comment]
Absolutely. Thank you. Feel free to close - or keep open as a tracking issue.

**Comment by jakirkham** [comment]
Thanks. We can leave it open :)

**Comment by jakirkham** [comment]
This seems to work now based on rerunning the code above with a recent `psutil`. Closing this out
