### ISSUE TITLE
v5.9.6

### ISSUE THREAD

**Issue by thewchan** [conda-forge/psutil-feedstock#72]
### Comment:

A package specifically pin v5.9.6, requesting a branch be created so I can PR against it to bring over this verion

CC: @gqmelo @jakirkham @nehaljwani @pelson

**Comment by jakirkham** [comment]
Sure added [`v5.9.6`]( https://github.com/conda-forge/psutil-feedstock/tree/v5.9.6 )

We may just want to merge that into `main` and delete it after

**Comment by thewchan** [comment]
Okay I can make a PR and you all can decide what to do with it

**Comment by jakirkham** [comment]
Sounds good

**Comment by mr-c** [comment]
https://github.com/conda-forge/psutil-feedstock/pull/75 was merged and [`psutil` 5.9.6 was released](https://anaconda.org/conda-forge/psutil/files?version=5.9.6), so this issue can probably be closed.
